kind: Namespace
apiVersion: v1
metadata:
  name: roboshop
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: prasanth-roboshop-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prasanth-roboshop-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: prasanth
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: prasanth-roboshop-role
  apiGroup: rbac.authorization.k8s.io