
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::200385471840:role/eksctl-spot-cluster-nodegroup-spo-NodeInstanceRole-1W78DJ5O3GBCC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::200385471840:user/prasanth-roboshop
      username: prasanth-roboshop
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-27T07:08:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1156"
  uid: 8f74cfb1-2d82-4314-a096-6a0045b3d1fd